# name: Run system-info.js

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Correct: Use 'uses' to call an action
      - name: Checkout code
        uses: actions/checkout@v3

      # Correct: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # You can set this to the version you need

      # Run your script
      - name: Run system-info.js
        run: node system-info.js
